INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('1', '0', 'Cotización aceptada por el cliente.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('2', '5', 'Tareas giradas a talleres.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('3', '10', 'Trabajo a Flote: Inspección abordo efectuada.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('4', '15', 'Trabajo en taller: Equipo desmontado - todo o partes en Taller.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('5', '25', 'Inspección terminada. Informes Técnicos, Recomendación Reparación y Listado Repuestos en poder de Cliente.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('6', '30', 'Recomendación de reparación aprobada. Cotización entregada al cliente.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('7', '35', 'Cotización aprobada por el Cliente.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('8', '40', 'Tareas emitidas a Talleres.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('9', '50', 'Repuestos recibidos por el Taller.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('10', '60', 'Proceso de Arme y Ajuste en taller.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('11', '70', 'Proceso de Arme y Ajuste en taller terminado.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('12', '75', 'Pruebas de Taller terminadas. Trabajo recibido por el Cliente e Inspectoría en Taller.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('13', '80', 'Equipo instalado abordo y no probado o trabajo a flote terminado abordo y no probado.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('14', '85', 'Trabajo recibido abordo por la Inspectoría y el Cliente. Inspección de Instalación aprobada.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('15', '95', 'Trabajo recibido por la Inspectoría y el cliente. Pruebas de Puerto aprobadas.', now(), now());
INSERT INTO `armada`.`nomenclaturasAvance` (`id`, `porcentaje`, `glosa`, `created_at`, `updated_at`) VALUES ('16', '100', 'Prueba de Mar aprobada. Trabajo terminado.', now(), now());

INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('1', 'Ingeniería', now(), now());
INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('2', 'Armamento', now(), now());
INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('3', 'Telecomunicaciones', now(), now());
INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('4', 'Electricidad', now(), now());
INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('5', 'Electrónica', now(), now());
INSERT INTO `armada`.`areas` (`id`, `nombrearea`, `created_at`, `updated_at`) VALUES ('6', 'Otra', now(), now());
